interval = 14
microprofit = 2
minrsiprofit = 65
checklost = 40

[thresholds]
low = 30
high = 70
persistence = 3
highpersistence = 2

[dma]
short = 10
long = 21
down = -0.025
up = 0.025

[macd]
short = 10
long = 21
signal = 9
down = -0.025
up = 0.025
persistence = 3
rsi = 35